# Generated by Django 4.0.3 on 2022-03-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Rating', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
